[lib]
proc-macro = true

[package]
name = "unc-vm-compiler-test-derive"
version.workspace = true
authors = ["Wasmer Engineering Team <engineering@wasmer.io>", "Hello Inc <hello@utnet.org>"]
edition = "2021"
license = "GPL-2.0-or-later"
description = "A macro to generate easily tests across compilers and engines"
keywords = ["unsafe", "body", "fn", "safety", "hygiene"]
categories = ["rust-patterns"]
publish = false

[lints]
workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[features]

[dev-dependencies]
pretty_assertions.workspace = true
trybuild.workspace = true
