[package]
name = "addkey-contract"
version = "0.1.0"
authors = ["Hello Inc <hello@utnet.org>"]
edition = "2018"

[workspace]
members = []


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
unc-sdk = "0.7.4"

[dev-dependencies]
borsh = { version = "1.4.0"}

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
# Opt into extra safety checks on arithmetic operations https://stackoverflow.com/a/64136471/249801
overflow-checks = true
