[package]
name = "keypair-generator"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
clap.workspace = true

unc-infra.workspace = true
unc-crypto.workspace = true
