[package]
name = "unc-vm-vm"
version.workspace = true
description = "Runtime library support for Wasmer"
categories = ["wasm"]
keywords = ["wasm", "webassembly"]
authors = ["Wasmer Engineering Team <engineering@wasmer.io>", "Hello Inc <hello@unc.com>"]
repository.workspace = true
license = "GPL-2.0-or-later"
readme = "README.md"
edition = "2021"
publish = true

[lints]
workspace = true

[dependencies]
backtrace.workspace = true
cfg-if.workspace = true
finite-wasm.workspace = true
indexmap.workspace = true
libc.workspace = true
memoffset.workspace = true
more-asserts.workspace = true
region.workspace = true
rkyv.workspace = true
thiserror.workspace = true
tracing.workspace = true
unc-vm-types.workspace = true
wasmparser.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
winapi.workspace = true

[build-dependencies]
cc.workspace = true

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
